authentik_host: https://your-authentik-instance.onrender.com
token: your-outpost-token

listen:
  http: 0.0.0.0:9000
  https: null

external_host: https://elkalyf-protected.onrender.com
internal_host: http://localhost:3000
