entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  file:
    directory: /etc/traefik
    watch: true

log:
  level: DEBUG

api:
  dashboard: true

http:
  routers:
    protected:
      rule: "Host(`elkalyf-protected.onrender.com`)"  # or your real domain
      entryPoints:
        - web
      service: authentik
  services:
    authentik:
      loadBalancer:
        servers:
          - url: "http://localhost:9000"
