version: '3.7'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--providers.file.filename=/etc/traefik/traefik.yml"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
    volumes:
      - ./authentik-proxy/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "443:443"

  authentik-outpost:
    image: ghcr.io/goauthentik/proxy:2025.2.2
    environment:
      - AUTHENTIK_HOST=https://auth.elkalyf.de
      - AUTHENTIK_TOKEN=your-outpost-token-here
      - AUTHENTIK_INSECURE=false
    volumes:
      - ./authentik-proxy/config.yml:/etc/authentik/config.yml

  your-app:
    image: your-app-image
    expose:
      - "3000"
